INSERT INTO AES_FORMATS VALUES(0, 'True/False');
INSERT INTO AES_FORMATS VALUES(0, 'Multiple Choice');
INSERT INTO AES_FORMATS VALUES(0, 'Multiple Select');
INSERT INTO AES_FORMATS VALUES(0, 'Drag and Drop');
INSERT INTO AES_FORMATS VALUES(0, 'Essay');
INSERT INTO AES_FORMATS VALUES(0, 'Short Answer');
INSERT INTO AES_FORMATS VALUES(0, 'Code Snippet');

INSERT INTO AES_CATEGORY VALUES(0, 'Java');
INSERT INTO AES_CATEGORY VALUES(0, 'SDET');
INSERT INTO AES_CATEGORY VALUES(0, '.Net');