CREATE TABLE AES_USERS(
  USER_ID NUMBER,
  EMAIL VARCHAR2(255),
  FIRSTNAME VARCHAR2(255),
  LASTNAME VARCHAR2(255),
  SALESFORCE NUMBER,
  RECRUITER_ID NUMBER,
  ROLE_ID NUMBER,
  DATE_PASS_ISSUED DATE);

CREATE TABLE AES_USER_TRAINERS(
  USER_ID NUMBER,
  TRAINER_ID NUMBER);
  
CREATE TABLE AES_ROLES(
  ROLE_ID NUMBER,
  ROLE_TITLE VARCHAR2(255));
  
CREATE TABLE AES_FILE_UPLOAD(
  FILE_ID NUMBER,
  FILE_URL VARCHAR2(255),
  GRADE NUMBER,
  QUESTION_ID NUMBER,
  ASSESSMENT_ID NUMBER);
  
CREATE TABLE AES_ASSESSMENT(
  ASSESSMENT_ID NUMBER,
  USER_ID NUMBER,
  GRADE NUMBER,
  TIME_LIMIT NUMBER,
  CREATED_TIMESTAMP DATE,
  FINISHED_TIMESTAMPT DATE);
  
CREATE TABLE AES_SECURITY(
  USER_ID NUMBER,
  PASS_WORD VARCHAR2(255),
  VALID NUMBER(0/1));

