/*******************************************************************************
   Create Tables
********************************************************************************/
CREATE TABLE AES_USERS(
  USER_ID NUMBER,
  EMAIL VARCHAR2(255),
  FIRSTNAME VARCHAR2(255),
  LASTNAME VARCHAR2(255),
  SALESFORCE NUMBER,
  RECRUITER_ID NUMBER,
  ROLE_ID NUMBER,
  DATE_PASS_ISSUED DATE
);
/
CREATE TABLE AES_USER_TRAINERS(
  USER_ID NUMBER,
  TRAINER_ID NUMBER
);
/
CREATE TABLE AES_ROLES(
  ROLE_ID NUMBER,
  ROLE_TITLE VARCHAR2(255)
);
/
CREATE TABLE AES_FILE_UPLOAD(
  FILE_ID NUMBER,
  FILE_URL VARCHAR2(255),
  GRADE NUMBER,
  QUESTION_ID NUMBER,
  ASSESSMENT_ID NUMBER
);
/
CREATE TABLE AES_ASSESSMENT(
  ASSESSMENT_ID NUMBER,
  USER_ID NUMBER,
  GRADE NUMBER,
  TIME_LIMIT NUMBER,
  CREATED_TIMESTAMP DATE,
  FINISHED_TIMESTAMP DATE,
  TEMPLATE_ID NUMBER
);
/
CREATE TABLE AES_SECURITY(
  USER_ID NUMBER,
  PASS_WORD VARCHAR2(255),
  VALID NUMBER
);
/
/*******************************************************************************
   Add Primary Keys
********************************************************************************/
ALTER TABLE AES_USERS
  ADD CONSTRAINT PK_USERS PRIMARY KEY  (USER_ID);
ALTER TABLE AES_USER_TRAINERS
  ADD CONSTRAINT PK_USER_TRAINERS PRIMARY KEY (USER_ID, TRAINER_ID);
ALTER TABLE AES_ROLES
  ADD CONSTRAINT PK_ROLES PRIMARY KEY (ROLE_ID);  
ALTER TABLE AES_FILE_UPLOAD
  ADD CONSTRAINT PK_FILE_UPLOAD PRIMARY KEY (FILE_ID);  
ALTER TABLE AES_ASSESSMENT
  ADD CONSTRAINT PK_ASSESSMENT PRIMARY KEY (ASSESSMENT_ID);  
ALTER TABLE AES_SECURITY
  ADD CONSTRAINT PK_SECURITY PRIMARY KEY (USER_ID);  
/*******************************************************************************
   Add Foreign Keys
********************************************************************************/  
ALTER TABLE AES_USERS
  ADD CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES AES_ROLES (ROLE_ID);
  
ALTER TABLE AES_USER_TRAINERS
  ADD CONSTRAINT FK_USER_TRAINERS_USER FOREIGN KEY (USER_ID) REFERENCES AES_USERS (USER_ID);
ALTER TABLE AES_USER_TRAINERS
  ADD CONSTRAINT FK_USER_TRAINERS_TRAINER FOREIGN KEY(TRAINER_ID) REFERENCES AES_USERS (USER_ID);  
  
--ALTER TABLE AES_FILE_UPLOAD
--  ADD CONSTRAINT FK_FILE_UPLOAD_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES AES_QUESTION(QUESTION_ID);
ALTER TABLE AES_FILE_UPLOAD
  ADD CONSTRAINT FK_FILE_UPLOAD_ASSESSMENT FOREIGN KEY (ASSESSMENT_ID) REFERENCES AES_ASSESSMENT(ASSESSMENT_ID);
  
ALTER TABLE AES_ASSESSMENT
  ADD CONSTRAINT FK_ASSESSMENT_USER FOREIGN KEY (USER_ID) REFERENCES AES_USERS(USER_ID);
--ALTER TABLE AES_ASSESSMENT
--  ADD CONSTRAINT FK_ASSESSMENT_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES AES_TEMPLATES(TEMPLATE_ID);  

ALTER TABLE AES_SECURITY
  ADD CONSTRAINT FK_SECURITY_USER FOREIGN KEY (USER_ID) REFERENCES AES_USERS(USER_ID);
/*******************************************************************************
   Add Other Constraints
********************************************************************************/  
ALTER TABLE AES_USERS
  MODIFY (EMAIL NOT NULL);
ALTER TABLE AES_USERS 
  MODIFY (FIRSTNAME NOT NULL);
ALTER TABLE AES_USERS 
  MODIFY (LASTNAME NOT NULL);
ALTER TABLE AES_USERS
  MODIFY (ROLE_ID NOT NULL);
ALTER TABLE AES_USERS
  MODIFY (DATE_PASS_ISSUED NOT NULL);
  
ALTER TABLE AES_ROLES
  MODIFY (ROLE_TITLE NOT NULL UNIQUE);
  
ALTER TABLE AES_ASSESSMENT
  MODIFY (USER_ID NOT NULL);
ALTER TABLE AES_ASSESSMENT
  MODIFY (CREATED_TIMESTAMP NOT NULL);
  
ALTER TABLE AES_SECURITY
  MODIFY (PASS_WORD NOT NULL);
ALTER TABLE AES_SECURITY
  ADD CONSTRAINT CHECK_VALID CHECK (VALID IN (0, 1));
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE USER_TRAINERS_SEQ;
DROP SEQUENCE ROLES_SEQ;
DROP SEQUENCE FILE_UPLOAD_SEQ;
DROP SEQUENCE ASSESSMENT_SEQ;
DROP SEQUENCE SECURITY_SEQ;  
CREATE SEQUENCE USERS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;
/
CREATE SEQUENCE USER_TRAINERS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;
/
CREATE SEQUENCE ROLES_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;
/
CREATE SEQUENCE FILE_UPLOAD_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;
/
CREATE SEQUENCE ASSESSMENT_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;
/
CREATE SEQUENCE SECURITY_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;
/
